/********************************************************************
* awareDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error awareDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableawareDict();
extern void G__cpp_setup_inheritanceawareDict();
extern void G__cpp_setup_typetableawareDict();
extern void G__cpp_setup_memvarawareDict();
extern void G__cpp_setup_globalawareDict();
extern void G__cpp_setup_memfuncawareDict();
extern void G__cpp_setup_funcawareDict();
extern void G__set_cpp_environmentawareDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "AwareRunSummaryFileMaker.h"
#include "AwareVariableSummary.h"
#include "AwareVariable.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__awareDictLN_string;
extern G__linked_taginfo G__awareDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__awareDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__awareDictLN_TTimeStamp;
extern G__linked_taginfo G__awareDictLN_AwareVariable;
extern G__linked_taginfo G__awareDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__awareDictLN_AwareVariableSummary;
extern G__linked_taginfo G__awareDictLN_maplEunsignedsPintcOAwareVariablecOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOAwareVariablegRsPgRsPgR;
extern G__linked_taginfo G__awareDictLN_maplEunsignedsPintcOAwareVariablecOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOAwareVariablegRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__awareDictLN_AwareRunSummaryFileMaker;
extern G__linked_taginfo G__awareDictLN_maplEstringcOAwareVariableSummarycOlesslEstringgRcOallocatorlEpairlEconstsPstringcOAwareVariableSummarygRsPgRsPgR;
extern G__linked_taginfo G__awareDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__awareDictLN_maplEunsignedsPintcOmaplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOmaplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgRsPgRsPgRsPgR;

/* STUB derived class for protected member access */
